name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    types: ["opened", "reopened", "synchronize"]
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tsc-check:
    runs-on: ubuntu-latest
    steps:
      # actions/checkout@v6.0.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      # ./.github/actions/node-setup
      - uses: ./.github/actions/node-setup
        with:
          command: tsc --noEmit

  test:
    needs: tsc-check
    runs-on: ubuntu-latest
    steps:
      # actions/checkout@v6.0.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      # ./.github/actions/node-setup
      - uses: ./.github/actions/node-setup
        with:
          command: npm run test:run && npm run test:coverage
      # actions/upload-artifact@v7.0.1
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        if: success()
        with:
          name: coverage-report
          path: coverage

  build-test:
    needs: tsc-check
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      # actions/checkout@v6.0.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      # ./.github/actions/node-setup
      - uses: ./.github/actions/node-setup
        with:
          command: npm run test:build
