name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    types: ["opened", "reopened", "synchronize"]
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      # actions/checkout@v6.0.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      # voidzero-dev/setup-vp@v1.10.0
      - uses: voidzero-dev/setup-vp@ca1c46663915d6c1042ae23bd39ab85718bfb0fa
        with:
          node-version: "24.15.0"
          cache: true

      # generate dist
      - run: vp build

      # format, lint, tsc
      - run: vp check

      # test and coverage
      - run: vp test run --coverage

      # e2e build test
      - run: vp run test:build
