name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    types: ["opened", "reopened", "synchronize"]
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Format, Lint, and Type Check
    runs-on: ubuntu-latest
    steps:
      # actions/checkout@v6.0.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      # voidzero-dev/setup-vp@v1.10.0
      - uses: voidzero-dev/setup-vp@ca1c46663915d6c1042ae23bd39ab85718bfb0fa
        with:
          node-version: "24.15.0"
          cache: true

      - run: vp check

  test:
    name: Test and Coverage
    runs-on: ubuntu-latest
    steps:
      # actions/checkout@v6.0.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      # voidzero-dev/setup-vp@v1.10.0
      - uses: voidzero-dev/setup-vp@ca1c46663915d6c1042ae23bd39ab85718bfb0fa
        with:
          node-version: "24.15.0"
          cache: true

      - run: vp test run --coverage

      # actions/upload-artifact@v7.0.1
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        if: success()
        with:
          name: coverage-report
          path: coverage

  build-test:
    name: E2E Build Test
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      # actions/checkout@v6.0.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      # voidzero-dev/setup-vp@v1.10.0
      - uses: voidzero-dev/setup-vp@ca1c46663915d6c1042ae23bd39ab85718bfb0fa
        with:
          node-version: "24.15.0"
          cache: true

      - run: vp run test:build
